### ISSUE TITLE
Node Modules: Vulnerabilities

### ISSUE THREAD

**Issue by djbreen7** [DevExpress/generator-testcafe-reporter#11]
**Summary**
The current state of the reporter has several dependency vulnerabilities. As of today, npm audit shows:
```
found 34 vulnerabilities (14 low, 13 moderate, 6 high, 1 critical) in 3755 scanned packages
  34 vulnerabilities require semver-major dependency updates.
```
[Full Report](https://github.com/DevExpress/generator-testcafe-reporter/files/2913147/npm_audit.txt)

**Expected Outcome**
- All vulnerable dependencies should be updated
- All functionality should remain the same

**Comment by AndreyBelym** [comment]
Thank you for contributing to TestCafe, I've published `generator-testcafe-reporter@2.1.1` with the fix. 🎉

**Comment by djbreen7** [comment]
Thanks for building testcafe and saving me from selenium!

**Comment by AndreyBelym** [comment]
Thank you for using TestCafe 😄
