### ISSUE TITLE
Report publish failed as `npm run publish-please` script run on terminal 

### ISSUE THREAD

**Issue by TestAndunR** [DevExpress/generator-testcafe-reporter#8]
[2018-06-21T11_47_16_490Z-debug.log](https://github.com/DevExpress/generator-testcafe-reporter/files/2123470/2018-06-21T11_47_16_490Z-debug.log)
**Description:**
Report plugin published failed as `npm run publish-please` executed on terminal, and generated the following attached error log file.

**Comment by AndreyBelym** [comment]
I apologize for the delayed response. It looks like `publish-please` as not installed in your system. Please remove `node_modules`, run `npm cache clean -f` & `npm install` and try again.
